create table "user_organisation_unit_ids" ("user_id" int8 not null, organisation_unit_ids varchar(255));
create table "users" (id int8 generated by default as identity, email varchar(255), firstname varchar(255), identityprovideruserobjectid uuid, lastname varchar(255), mainorganisationunitid varchar(255), mainorganisationunitname varchar(255), managerref varchar(255), mobilephone varchar(255), resourceid varchar(255), username varchar(255), usertype varchar(255), primary key (id));
alter table if exists "users" add constraint UK_tmnk5grfniihp9dwd7fbo9otu unique (resourceid);
alter table if exists "user_organisation_unit_ids" add constraint FKiodmrttou42ofbfdq67140yko foreign key ("user_id") references "users";
