novari:
  kafka:
    default-replicas: 1
    topic:
      domain-context: kontroll
      org-id: ${fint.org-id}
    application-id: ${fint.application-id}
spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}

