spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${fint.database.username}
    url: ${fint.database.url}
    password: ${fint.database.password}
  flyway:
    locations: classpath:db/migration/
    lock-retry-count: 300
