fint:
  org-id: ''
  application-id: fint-kontroll-user-catalog
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  integration:
    service:
      authorized-role: https://role-catalog.vigoiks.no/vigo/samtykke/user
  kontroll:
    user-catalog:
      pagesize: 50
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
  profiles:
    include:
      - kontroll-kafka
      - kontroll-postgres
      - kontroll-schema-generation
logging:
  level:
    root: INFO
    org.apache.kafka: INFO

