fint:
  org-id: fintlabs.no
  kafka:
    default-replicas: 1
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${fint.application-id}
  kontroll:
    role-catalog:
      pagesize: 50
    opa:
      url: http://localhost:8181/v1/data/accessmanagement
    authorization:
      authorized-role: https://role-catalog.vigoiks.no/vigo/samtykke/user
      authorized-org-id: vigo.no
    externalusers: yes
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id: ${fint.client-id}
            client-secret: ${fint.client-secret}
            provider: fint-idp
            scope: fint-client
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    properties:
      javax:
      hibernate:
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    hikari:
      schema: users
  flyway:
    locations: classpath:db/migration/
    lock-retry-count: 300
    #baseline-on-migrate: true


server:
  port: 8083

