fint:
  org-id: fintlabs.no
  flyt:
    resource-gateway:
      authorization:
        enable: true
  client:
    base-url: https://beta.felleskomponent.no
  kafka:
    default-replicas: 1

  kontroll:
    user-catalog:
      load-test-users: true
      number-of-test-users: 20
      synthetic-user-token:
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
      hikari:
        schema: fylke
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
#        registration:
#          fint:
#            authorization-grant-type: password
#            client-id:
#            client-secret:
#            provider: fint-idp
#            scope: fint-client

