apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-user-catalog
  app.kubernetes.io/instance: fint-kontroll-user-catalog_fintlabs-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
      - op: replace
        path: "/spec/env/0/value"
        value: "https://role-catalog.vigoiks.no/vigo/kontroll/user"
      - op: replace
        path: "/spec/env/1/value"
        value: "vigo.no"
      - op: replace
        path: "/spec/env/2/value"
        value: "fintlabs-no-fint-kontroll-user-catalog"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "fintlabs-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "fintlabs-no.kontroll.*"
      - op: replace
        path: "/spec/ingress/basePath"
        value: '/fintlabs-no/api/users'
      - op: replace
        path: "/spec/url/basePath"
        value: "/fintlabs-no"
      - op: replace
        path: "/spec/url/hostname"
        value: "kontroll.novari.no"
      - op: replace
        path: "/spec/observability/metrics/path"
        value: "/fintlabs-no/actuator/prometheus"
      - op: add
        path: "/spec/resources"
        value:
          limits:
            cpu: "1000m"
            memory: "2000Mi"
          requests:
            cpu: "500m"
            memory: "500Mi"
    target:
      kind: Application
      name: fint-kontroll-user-catalog

