create table user_organisation_unit_ids
(
    user_id               bigint not null
        constraint fkiodmrttou42ofbfdq67140yko
            references users,
    organisation_unit_ids varchar(255)
);


create table users
(
    id                           bigint generated by default as identity
        primary key,
    email                        varchar(255),
    firstname                    varchar(255),
    identityprovideruserobjectid uuid,
    lastname                     varchar(255),
    mainorganisationunitid       varchar(255),
    mainorganisationunitname     varchar(255),
    managerref                   varchar(255),
    mobilephone                  varchar(255),
    resourceid                   varchar(255)
        constraint uk_tmnk5grfniihp9dwd7fbo9otu
            unique,
    username                     varchar(255),
    usertype                     varchar(255)
);