CREATE TABLE external_user
(
    id                               bigint generated by default as identity primary key,
    first_name                       VARCHAR(255),
    last_name                        VARCHAR(255),
    user_type                        VARCHAR(255),
    user_name                        VARCHAR(255),
    identity_provider_user_object_id UUID,
    main_organisation_unit_name      VARCHAR(255),
    main_organisation_unit_id        VARCHAR(255),
    mobile_phone                     VARCHAR(255),
    email                            VARCHAR(255)
);