apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
    app.kubernetes.io/name: fint-kontroll-user-catalog
    app.kubernetes.io/instance: fint-kontroll-user-catalog_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-kontroll
    fintlabs.no/team: bas
    fintlabs.no/org-id: fintlabs.no
resources:
  - flais.yaml
  - config-map.yaml
